services:
  - type: web
    name: order-management-api
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_NAME
        value: OrderManager
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://order-management-api.onrender.com
      - key: APP_KEY
        value: base64:/UQZ4nsscfJzQlKPBkJlrkMjbDrzE6aP41E5IgGBvlY=
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /var/www/html/database/database.sqlite
      - key: LOG_CHANNEL
        value: stack
